name: bohra_calender
description: Bohra Calender Plus

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 8.0.0+11

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_qiblah: ^2.0.2
  flutter_svg: ^0.23.0+1
  intl: ^0.17.0
  location: ^4.3.0
  dio: ^4.0.4
  path_provider: ^2.0.7
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^9.2.0
  weather_icons: ^3.0.0
  hijri: ^3.0.0
  http: ^0.13.4
  basic_utils: ^3.9.4
  flutter_cached_pdfview: ^0.4.1
  audio_video_progress_bar: ^0.10.0
  sleek_circular_slider: ^2.0.1
  get_it: ^7.2.0
  add_2_calendar: ^2.1.2
  just_audio: ^0.9.18
  objectbox: ^1.3.0
  objectbox_flutter_libs: ^1.3.0
  rflutter_alert: ^2.0.4
  flutter_native_timezone: ^2.0.0
  daylight: ^2.0.0
  flutter_local_notifications: ^9.2.0
  timezone: ^0.8.0
  url_launcher: ^6.0.20
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  geocoding: ^2.0.4
  lat_lng_to_timezone: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^1.0.0
  objectbox_generator: ^1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon.jpg"



flutter:


  uses-material-design: true

  fonts:
    - family: Number
      fonts:
        - asset: assets/fonts/Hubballi-Regular.ttf
    - family: Arabic
      fonts:
        - asset: assets/fonts/noorehira.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 800
        - asset: assets/fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 900

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
